### ISSUE TITLE
使用时报错，无法正常回复

### ISSUE THREAD

**Issue by simontombu** [EuDs63/nonebot-plugin-yesman#2]
报错日志如下：

07-29 16:59:16 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-yesman, lineno=35) failed.
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/LinuxQQBot/.venv/lib/python3.10/site-packages/nonebot-plugin-yesman/__init__.py", line 39, in agree
    print(event.user_id)
ValueError: I/O operation on closed file.

**Comment by EuDs63** [comment]
根据报错信息来看，问题出在init.py", line 39, in agree print(event.user_id)
但报的错是ValueError: I/O operation on closed file.这就很奇怪。
我暂时没有解决的思路，抱歉
